registry="term:node_glyphs"

[values]
"env:access_point"="@@"
# Considered alternatives "ðŸƒ ", "â™ â™¥", "==", "++", "&]", "â–¡]"
"pickup:card"   =["ðŸ‚  ", "yellow"]
"pickup:mon"    =["$$", "yellow"]

"Attack Dog"    =["çŠ¬", [252, 187, 0]]
"Ballista"      =["bl", [0, 217, 165]]
"Bit Man"       =["01", [182, 252, 0]]
"Black Widow"   =["bw", [27, 231, 0]]
"Boss"          =["æ­»", [252, 98, 0]]
"Bug"           =["b ", [132, 252, 0]]
"Buzzbomb"      =["BB", [0, 144, 252]]
"Catapult"      =["cp", [0, 217, 165]]
"Clog"          =["c1", [0, 252, 203]]
"Clog.02"       =["c2", [0, 252, 203]]
"Clog.03"       =["c3", [0, 252, 203]]
"Data Doctor Pro"=["DD", [0, 51, 249]]
"Data Doctor"   =["dd", [0, 51, 249]]
"Fiddle"        =["fd", [0, 144, 252]]
"Fire Wall"     =["é‡‘", [252, 98, 0]]
"Golem Clay"    =["gc", [0, 252, 249]]
"Golem Mud"     =["gm", [0, 252, 249]]
"Golem Stone"   =["gs", [0, 252, 249]]
"Guard Dog"     =["GD", [252, 187, 0]]
"Guard Pup"     =["gd", [252, 187, 0]]
"Guru"          =["GR", [0, 252, 203]]
"Hack 2.0"      =["h2", [0, 199, 252]]
"Hack 3.0"      =["h3", [0, 199, 252]]
"Hack"          =["hk", [0, 199, 252]]
"Heisenbug"     =["hb", [132, 252, 0]]
"Laser Satellite"=["ls", [0, 252, 203]]
"Logic Bomb"    =["LB", [0, 144, 252]]
"Mandelbug"     =["mb", [132, 252, 0]]
"Medic"         =["md", [0, 51, 249]]
"Memory Hog"    =["MH", [182, 252, 0]]
"Mobile Tower"  =["MT", [0, 252, 149]]
"Radar"         =["RD", [252, 241, 0]]
"Satellite"     =["s ", [0, 252, 203]]
"Seeker 2.0"    =["s2", [0, 217, 165]]
"Seeker 3.0"    =["s3", [0, 217, 165]]
"Seeker"        =["sk", [0, 217, 165]]
"Sensor"        =["sn", [252, 241, 0]]
"Sentinel 2.0"  =["SL", [252, 152, 0]]
"Sentinel 3.0"  =["äºº", [252, 152, 0]]
"Sentinel"      =["sl", [252, 152, 0]]
"Slingshot"     =[">-", [0, 217, 165]]
"Sonar"         =["SN", [252, 241, 0]]
"Sumo"          =["å¤§", [182, 252, 0]]
"Tarantula"     =["tt", [27, 231, 0]]
"Tower"         =["tw", [0, 252, 149]]
"Turbo Deluxe"  =["TB", [0, 144, 252]]
"Turbo"         =["tb", [0, 144, 252]]
"Warden"        =["wd", [252, 241, 0]]
"Warden+"       =["WD", [252, 241, 0]]
"Warden++"      =["wd", [252, 241, 0]]
"Watchman SP"   =["ç›®", [252, 37, 138]]
"Watchman X"    =["(O", [252, 37, 138]]
"Watchman"      =["(o", [252, 37, 138]]
"Wizard"        =["WZ", [0, 252, 149]]
"Wolf Spider"   =["ws", [27, 231, 0]]
