registry="term:node_glyphs"

[values]
"env:access_point"="@@"
# Considered alternatives "ðŸƒ ", "â™ â™¥", "==", "++", "&]", "â–¡]"
"pickup:card"   =["ðŸ‚  ", "yellow"]
"pickup:mon"    =["$$", "yellow"]

"Attack Dog"    =["çŠ¬", "darkred"]
"Ballista"      ="bl"
"Bit Man"       =["01", [182, 252, 0]]
"Black Widow"   ="bw"
"Boss"          ="æ­»"
"Bug"           =["b ", [132, 252, 0]]
"Buzzbomb"      ="BB"
"Catapult"      ="cp"
"Clog"          ="c1"
"Clog.02"       ="c2"
"Clog.03"       ="c3"
"Data Doctor Pro"="DD"
"Data Doctor"   ="dd"
"Fiddle"        ="fd"
"Fire Wall"     ="é‡‘"
"Golem Clay"    ="gc"
"Golem Mud"     ="gm"
"Golem Stone"   ="gs"
"Guard Dog"     ="GD"
"Guard Pup"     ="gd"
"Guru"          ="GR"
"Hack 2.0"      ="h2"
"Hack 3.0"      ="h3"
"Hack"          =["hk", [0, 199, 252]]
"Heisenbug"     ="hb"
"Laser Satellite"="ls"
"Logic Bomb"    ="LB"
"Mandelbug"     ="mb"
"Medic"         ="md"
"Memory Hog"    ="MH"
"Mobile Tower"  ="MT"
"Radar"         ="RD"
"Satellite"     ="s "
"Seeker 2.0"    ="s2"
"Seeker 3.0"    ="s3"
"Seeker"        ="sk"
"Sensor"        ="sn"
"Sentinel 2.0"  ="SL"
"Sentinel 3.0"  ="äºº"
"Sentinel"      ="sl"
"Slingshot"     =[">-", [0, 217, 165]]
"Sonar"         ="SN"
"Sumo"          ="å¤§"
"Tarantula"     ="tt"
"Tower"         ="tw"
"Turbo Deluxe"  ="TB"
"Turbo"         ="tb"
"Warden"        ="wd"
"Warden+"       ="WD"
"Warden++"      ="wd"
"Watchman SP"   ="ç›®"
"Watchman X"    ="(O"
"Watchman"      ="(o"
"Wizard"        ="WZ"
"Wolf Spider"   ="ws"